<<<<<<< HEAD

=======
>>>>>>> be3faba605c07636be6ee056ab27b1e610d4005f
name: Deploy Docs

on:
  push:
    branches:
<<<<<<< HEAD
      - main
=======
      - vuepress
>>>>>>> be3faba605c07636be6ee056ab27b1e610d4005f

permissions:
  contents: write

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # if your docs needs submodules, uncomment the following line
          # submodules: true

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8


      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install Deps
        run: |
          corepack enable
          pnpm install --frozen-lockfile

      - name: Build Docs
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          pnpm run docs:build
          > docs/.vuepress/dist/.nojekyll

      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # Deploy Docs
          branch: gh-pages
          folder: docs/.vuepress/dist
